name: Standard Test
on: [push]
jobs:
  build-lint-test:
    name: Build, lint, test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Install Dependencies
        run:  nix run .#install-deps

      - name: Lint
        run:  nix run .#lint
      
      - name: Run Tests
        run:  nix run .#test-bot
        env:
          TEST_POLYGON_RPC: ${{ secrets.CI_DEPLOY_POLYGON_RPC_URL }}