name: Standard Test
on: [push]
jobs:
  build-lint-test:
    name: Build, lint, test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Prepare Sushi Lib
        run: ./prep-sushi.sh

      - name: Install Dependencies
        run:  nix develop -c npm install

      - name: Lint
        run:  nix develop -c npm run lint
      
      - name: Run Tests
        run:  nix develop -c npm test
        env:
          TEST_POLYGON_RPC: ${{ secrets.CI_DEPLOY_POLYGON_RPC_URL }}
          TEST_BASE_RPC: ${{ secrets.CI_DEPLOY_BASE_RPC_URL }}
          TEST_FLARE_RPC: ${{ secrets.RPC_URL_FLARE_FORK }}
          TEST_ETH_RPC: ${{ secrets.RPC_URL_ETHEREUM_FORK }}
          TEST_BSC_RPC: ${{ secrets.CI_DEPLOY_BSC_RPC_URL }}
          TEST_ARBITRUM_RPC: ${{ secrets.CI_DEPLOY_ARBITRUM_RPC_URL }}