name: Standard Test
on: [push]
jobs:
  build-lint-test:
    name: Build, lint, test
    strategy:
      matrix:
        chain: [POLYGON, ARBITRUM, ETH, FLARE, BSC, BASE]
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Set RPC
        run: echo "TEST_${{ matrix.chain }}_RPC=CI_DEPLOY_${{ matrix.chain }}_RPC_URL" >> $GITHUB_ENV

      - name: Prepare Sushi Lib
        run: ./prep-sushi.sh

      - name: Install Dependencies
        run:  nix develop -c npm install

      - name: Lint
        run:  nix develop -c npm run lint
      
      - name: Run Tests
        run:  nix develop -c npm test