name: Standard Test
on: [push]
jobs:
  build-lint-test:
    name: Build, lint, test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Install Dependencies
        run:  nix develop -c npm install

      - name: Lint
        run:  nix develop -c npm run lint
      
      - name: Run Tests
        run:  nix develop -c npm test
        env:
          TEST_POLYGON_RPC: ${{ secrets.CI_DEPLOY_POLYGON_RPC_URL }}